service: loanpro-challenge-aws-lambda-backend

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-1

functions:
  authenticate:
    handler: dist/index.authenticate
  processarithmetic:
    handler: dist/index.processUserArithmeticOperation
  retrieverecord:
    handler: dist/index.retrieveUserOperationsRecord
  
